install.packages("arules")
install.packages("arulesViz")
install.packages("RColorBrewer")
library(arules)
library(arulesViz)
library(RColorBrewer)
data("Groceries")
rule<-apriori(Groceries,parameter = list(support=0.002,confidence=0.5))
inspect(rule[1:10])
itemFrequencyPlot(Groceries, topN = 10) 
plot(rule,method="graph")